Models/ApodViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAppNASA.Models
{
    public class ApodViewModel
    {
        public string? Copyright { get; set; }

        public DateTime Date { get; set; }

        public string? Explanation { get; set; }

        public string? Title { get; set; }

        public string? Url { get; set; }
    }
}

Models/EpicViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Drawing;

namespace WebAppNASA.Models
{
    public class EpicViewModel
    {
        public string? Identifier;

        public string? Caption;

        public string? Image;

        public DateTime Date;

        public string? Path;
    }
}

Models/ErrorViewModel.cs
namespace WebAppNASA.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/RoversViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAppNASA.Models
{
    public class RoversViewModel
    {
        public string? Id { get; set; }
        public string? Img_src { get; set; }
        public string? Earth_date { get; set; }
    }
}

Controllers/ApodController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.MSIdentity.Shared;
using Newtonsoft.Json;
using NuGet.Protocol;
using WebAppNASA.Models;
using static System.Net.WebRequestMethods;

namespace WebAppNASA.Controllers
{
    public class ApodController : Controller
    {
        private readonly HttpClient _httpClient;

        public ApodController(IHttpClientFactory httpClientFactory)
        { 
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://api.nasa.gov/");
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var response = await _httpClient.GetAsync("planetary/apod?api_key=DEMO_KEY");

                if (response.IsSuccessStatusCode)
                {
                    var content = await response.Content.ReadAsStringAsync();
                    var _apod = JsonConvert.DeserializeObject<ApodViewModel>(content);

                    return View("Index", _apod);
                }
            }
            catch (Exception)
            {
                throw;
            }
            return View();
        }
    }
}

Controllers/EpicController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Drawing;
using System.Net.Http;
using WebAppNASA.Models;
using static System.Net.WebRequestMethods;

namespace WebAppNASA.Controllers
{
    public class EpicController : Controller
    {
        private readonly HttpClient _httpClientList;
        private readonly HttpClient _httpClient;
        private readonly EpicViewModel _epicModel;

        public EpicController(IHttpClientFactory httpClientFactory)
        {
            _httpClientList = httpClientFactory.CreateClient();
            _httpClientList.BaseAddress = new Uri("https://api.nasa.gov/");

            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://api.nasa.gov/");

            _epicModel = new EpicViewModel();
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                var response = await _httpClientList.GetAsync("EPIC/api/natural?api_key=DEMO_KEY");
                
                if (response.IsSuccessStatusCode)
                {
                    //Read and Deserialize object for call at the action that return list of Epic
                    var content = await response.Content.ReadAsStringAsync();
                    var _epicList = JsonConvert.DeserializeObject<List<EpicViewModel>>(content);

                    if (_epicList != null)
                    {
                        _epicModel.Identifier = _epicList[0].Identifier;
                        _epicModel.Caption = _epicList[0].Caption;
                        _epicModel.Image = _epicList[0].Image;
                        _epicModel.Date = _epicList[0].Date;

                        var dateFormat = _epicList[0].Date.ToString("yyyy/MM/dd");

                        //Read and Deserialize object for call at the action that return one image (the firs image of list). The route is a string made up of several parameters from the previous query
                        _epicModel.Path = "https://api.nasa.gov/EPIC/archive/natural/" + dateFormat + "/png/" + _epicList[0].Image.ToString() + ".png?api_key=DEMO_KEY";

                        return View("Index", _epicModel);
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }

            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAppNASA.Models;

namespace WebAppNASA.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RoversController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using WebAppNASA.Models;

namespace WebAppNASA.Controllers
{
    public class RoversController : Controller
    {
        private readonly HttpClient _httpClient;
        private RoversViewModel _rovers;


        public RoversController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://api.nasa.gov/");

            _rovers = new RoversViewModel();
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var response = await _httpClient.GetAsync("mars-photos/api/v1/rovers/curiosity/photos?sol=1000&page=2&api_key=DEMO_KEY");

                if (response.IsSuccessStatusCode)
                {
                    var content = await response.Content.ReadAsStringAsync();

                    if (content != null)
                    {
                        JObject objeto = JObject.Parse(content);
                        _rovers.Id = objeto["photos"][0]["id"].ToString();
                        _rovers.Img_src = objeto["photos"][0]["img_src"].ToString();
                        _rovers.Earth_date = objeto["photos"][0]["earth_date"].ToString();

                        return View("Index", _rovers);
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }

            return View();
        }
    }
}

Views/Apod/Index.cshtml
@model ApodViewModel


<!DOCTYPE html>
<html>
<head>
    <title>Image of the day</title>
</head>
<body>
    <h1>APOD</h1>
    <br />
    <div display="flex" flex-wrap="wrap">
        <div class="row" >
            <div class="col"  style="width:30%; align-content:center">
                <p></p>
                <img src="@Html.DisplayFor(modelItem => Model.Url)" alt="@Html.DisplayFor(modelItem => Model.Title)" style="width:100%" />
            </div>
            <div class="col" style="align-content:center">
                <p><h2>@Html.DisplayFor(modelItem => Model.Title)</h2> </p>
                <p>Date: @Html.DisplayFor(modelItem => Model.Date)</p>
                <p><h4>@Html.DisplayFor(modelItem => Model.Explanation)</h4></p>
                <p>Copyright(*): @Html.DisplayFor(modelItem => Model.Copyright)</p>
                <p><small>(*)Some photos come without copyright</small></p>
            </div>
        </div>
    </div>
</body>
</html>

Views/Epic/Index.cshtml
@model EpicViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>EPIC</h1>

<div display="flex" flex-wrap="wrap">
    <div class="row">
        <div class="col" style="width:50%; align-content:center">
            <img src="@Html.DisplayFor(modelItem => Model.Path)" style="width:100%" />
        </div>
        <div class="col" style="align-content:center; width:50%">
            <h5>Date: @Html.DisplayFor(modelItem => Model.Date)</h5>
            <h5>Identifier: @Html.DisplayFor(modelItem => Model.Identifier)</h5>
            <h5>Name: @Html.DisplayFor(modelItem => Model.Image)</h5>
            <h5>Caption: @Html.DisplayFor(modelItem => Model.Caption)</h5>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body style="background:url(/Images/Jupiter.jpg); background-repeat:no-repeat; background-size:cover; margin:0;" >

<h1 class="display-4" style="color:white">Bienvenido</h1>
<br />
<div class="row">

       <div class="col" style="text-align:justify; color:white;  padding-right:200px">
                <p>
                    La NASA tiene un portal API cuyo objetivo es dar a conocer datos, incluyendo imágenes e información desde hace ya algunos años. Podemos ver noticias, datos de meteorología espacial, informes de patentes, datos de los proyectos tecnológicos, de satélites, de exoplanetas, y un sinfín de información.</p>
                <p> Esta página es un ensayo para jugar un poco con las APIs públicas de la NASA y consta de tres partes: </p>
                <p> <b>- APOD:</b> La imagen astronómica del día seleccionada por la NASA.</p>
                <p> <b>- EPIC</b> (Earth Polycromatic Imaging Camera) de DSCOVR: Las cámaras de imágenes policromáticas capturan cada día varias imágenes de la tierra junto a su información. También captura imágenes únicas de ciertos eventos astronómicos como la luna.</p>
                <p> <b>- MARS ROVER:</b> Imágenes(*) de Marte captadas por las Rovers Curiosity, Opportunity y Spirit. </p>
                <p><small>(*)De las 25 fotos que se reciben al hacer la consulta de Curiosity, se ha escogido sólo una. </small></p>
       </div>
       <div class="col">
       </div>
</div>
</body>
</html>

Views/Rovers/Index.cshtml
@model RoversViewModel

<h1>ROVERS</h1>
<br />
<div display="flex" flex-wrap="wrap">
    <div class="row">
        <div class="col" style="width:30%; align-content:center">
            <p></p>
            <img src="@Html.DisplayFor(modelItem => Model.Img_src)"  style="width:100%" />
        </div>
        <div class="col" style="align-content:center">
            <h5><p>Rovers Name: CURIOSITY</p></h5>
            <h5><p>Id: @Html.DisplayFor(modelItem => Model.Id)</p></h5>
            <h5><p>Earth Date: @Html.DisplayFor(modelItem => Model.Earth_date)</p></h5>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppNASA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppNASA.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppNASA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Apod" asp-action="Index"><b>APOD</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Epic" asp-action="Index"><b>EPIC</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rovers" asp-action="Index"><b>ROVERS</b></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebAppNASA 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>